import Head from 'next/head'
// import { Intro } from '@/components';
import Link from 'next/link';
import Box from '@mui/material/Box'; 
import { Typography } from '@mui/material';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{
            marginTop: {xl:'8rem', lg:'6rem', md:'4rem', xs:'2rem'}
          }}>
        {/* <Intro isButtonSet/> */}
        <Link href={'/dashboard'} passHref>
          <Typography variant={'h6'} textAlign={'center'}>
            Regresa al dashboard o al login
          </Typography>
        </Link>
      </Box>
    </>
  )
}
